import { monokaiDimmed, defaultSettingsMonokaiDimmed } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "monokai-dimmed";
export const label = "Monokai Dimmed";
export const isDark = true;
export const uiTheme = "dark";
export const extension = monokaiDimmed;
export const settings = defaultSettingsMonokaiDimmed;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/monokai-dimmed.ts" });
