import { aura, defaultSettingsAura } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "aura";
export const label = "Aura";
export const isDark = true;
export const uiTheme = "dark";
export const extension = aura;
export const settings = defaultSettingsAura;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/aura.ts" });
