import { gruvboxDark, defaultSettingsGruvboxDark } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "gruvbox-dark";
export const label = "Gruvbox Dark";
export const isDark = true;
export const uiTheme = "dark";
export const extension = gruvboxDark;
export const settings = defaultSettingsGruvboxDark;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/gruvbox-dark.ts" });
