import { githubDark, defaultSettingsGithubDark } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "github-dark";
export const label = "GitHub Dark";
export const isDark = true;
export const uiTheme = "dark";
export const extension = githubDark;
export const settings = defaultSettingsGithubDark;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/github-dark.ts" });
