import { abyss, defaultSettingsAbyss } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "abyss";
export const label = "Abyss";
export const isDark = true;
export const uiTheme = "dark";
export const extension = abyss;
export const settings = defaultSettingsAbyss;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/abyss.ts" });
