import { solarizedDark, defaultSettingsSolarizedDark } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "solarized-dark";
export const label = "Solarized Dark";
export const isDark = true;
export const uiTheme = "dark";
export const extension = solarizedDark;
export const settings = defaultSettingsSolarizedDark;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/solarized-dark.ts" });
