import { tokyoNightDay, defaultSettingsTokyoNightDay } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "tokyo-night-day";
export const label = "Tokyo Night Day";
export const isDark = false;
export const uiTheme = "light";
export const extension = tokyoNightDay;
export const settings = defaultSettingsTokyoNightDay;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/tokyo-night-day.ts" });
