import { tomorrowNightBlue, defaultSettingsTomorrowNightBlue } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "tomorrow-night-blue";
export const label = "Tomorrow Night Blue";
export const isDark = true;
export const uiTheme = "dark";
export const extension = tomorrowNightBlue;
export const settings = defaultSettingsTomorrowNightBlue;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/tomorrow-night-blue.ts" });
