import { xcodeDark, defaultSettingsXcodeDark } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "xcode-dark";
export const label = "Xcode Dark";
export const isDark = true;
export const uiTheme = "dark";
export const extension = xcodeDark;
export const settings = defaultSettingsXcodeDark;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/xcode-dark.ts" });
