import { andromeda, defaultSettingsAndromeda } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "andromeda";
export const label = "Andromeda";
export const isDark = true;
export const uiTheme = "dark";
export const extension = andromeda;
export const settings = defaultSettingsAndromeda;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/andromeda.ts" });
