import { material, defaultSettingsMaterial } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "material";
export const label = "Material";
export const isDark = true;
export const uiTheme = "dark";
export const extension = material;
export const settings = defaultSettingsMaterial;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/material.ts" });
