import { sublime, defaultSettingsSublime } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "sublime";
export const label = "Sublime";
export const isDark = true;
export const uiTheme = "dark";
export const extension = sublime;
export const settings = defaultSettingsSublime;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/sublime.ts" });
