import { darcula, defaultSettingsDarcula } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "darcula";
export const label = "Darcula";
export const isDark = true;
export const uiTheme = "dark";
export const extension = darcula;
export const settings = defaultSettingsDarcula;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/darcula.ts" });
