import { whiteDark, defaultSettingsWhiteDark } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "white-dark";
export const label = "White Dark";
export const isDark = true;
export const uiTheme = "dark";
export const extension = whiteDark;
export const settings = defaultSettingsWhiteDark;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/white-dark.ts" });
