import { consoleDark, defaultSettingsConsoleDark } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "console-dark";
export const label = "Console Dark";
export const isDark = true;
export const uiTheme = "dark";
export const extension = consoleDark;
export const settings = defaultSettingsConsoleDark;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/console-dark.ts" });
