import { materialDark, defaultSettingsMaterialDark } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "material-dark";
export const label = "Material Dark";
export const isDark = true;
export const uiTheme = "dark";
export const extension = materialDark;
export const settings = defaultSettingsMaterialDark;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/material-dark.ts" });
