import { tokyoNight, defaultSettingsTokyoNight } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "tokyo-night";
export const label = "Tokyo Night";
export const isDark = true;
export const uiTheme = "dark";
export const extension = tokyoNight;
export const settings = defaultSettingsTokyoNight;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/tokyo-night.ts" });
