import { duotoneDark, defaultSettingsDuotoneDark } from '@uiw/codemirror-themes-all';
import { registerTheme } from '../../../src/lib/theme/registry';
import { __registerTheme } from '../../../packages/notron-sdk/src/api/theming';
export const id = "duotone-dark";
export const label = "Duotone Dark";
export const isDark = true;
export const uiTheme = "dark";
export const extension = duotoneDark;
export const settings = defaultSettingsDuotoneDark;
registerTheme(id, { extension, settings, isDark, label, uiTheme });
__registerTheme({ id, label, uiTheme, path: "./themes/duotone-dark.ts" });
